In [1]:
from numpy import loadtxt
from keras.models import load_model

Using TensorFlow backend.


In [2]:
model = load_model('model1.h5')

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential, Model
train_data_dir = "D:/Dataset/Test"
batch_size = 13
img_height = 208
img_width = 176
numClasses=4
validation_datagen= ImageDataGenerator(
        rescale= 1./255)
train_generator=validation_datagen.flow_from_directory(
        train_data_dir, target_size= (img_height, img_width),
        batch_size= batch_size,
        class_mode= 'categorical',
        shuffle=False)

num_test=1279

import numpy as np
x_pred = model.predict_generator(train_generator,num_test // batch_size+1)
x_pred = np.argmax(x_pred, axis=1)
print('Confusion Matrix')
print(confusion_matrix(train_generator.classes, x_pred))

Found 1279 images belonging to 4 classes.
Confusion Matrix
[[ 69   2  47  61]
 [  3   3   1   5]
 [  7   0 544  89]
 [  7   0 104 337]]


In [16]:
target_names = ['MildDemented', 'Modearteddemented1', 'NonDemented','VeryMildDemented']
print(classification_report(train_generator.classes, x_pred, target_names=target_names))


                    precision    recall  f1-score   support

      MildDemented       0.80      0.39      0.52       179
Modearteddemented1       0.60      0.25      0.35        12
       NonDemented       0.78      0.85      0.81       640
  VeryMildDemented       0.68      0.75      0.72       448

          accuracy                           0.75      1279
         macro avg       0.72      0.56      0.60      1279
      weighted avg       0.75      0.75      0.73      1279

